### ISSUE TITLE
Refactor Data context file

### ISSUE THREAD

**Issue by Nathan-Somto** [RICHYDOS/EliteMart#16]
I have been following you guys project because  i want to contribute to open source more.
one thing i noticed is the data context file in the frontend. it can be refactored, rather than having multiple contexts and states you can follow the flux pattern and make use of the useReducer hook to make the code look cleaner.
having a lot of context like that is not good for performance and you can opt for other solutions like  a state management library. but overall the project looks good
Here are some links if you are interested  in learning more

https://stackoverflow.com/questions/66786825/what-are-the-pros-and-cons-on-using-react-context-api-with-the-usereducer-hook

https://www.freecodecamp.org/news/how-to-use-flux-in-react-example/

https://dev.to/mgustus/react-different-types-of-state-management-3m6n

https://react.dev/reference/react/useReducer

**Comment by Honour-Boy** [comment]
Thanks for your contribution. The reason why I chose to use the useContext hook is that it provides an easy setup and allows data to be passed around efficiently. As an Amateur in React, I initially considered using the Redux library for state management but found it complex to grasp at that time. I plan to explore Redux and the useReducer hook in the future to understand how to implement them effectively. Additionally, I will clean up the dataContext file by removing any unused contexts from previous projects cause most of them there are not being used. Once again, thank you for your valuable input.
